name: mobiledevtest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  dio: ^4.0.4
  shared_preferences: ^2.0.8
  provider: ^6.0.4
  loader_overlay: ^2.1.0
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/png/
    - assets/images/svg/


  fonts:
    - family: Mulish
      fonts:
        - asset: assets\fonts\mullish\Mulish-Black.ttf
        - asset: assets\fonts\mullish\Mulish-BlackItalic.ttf
        - asset: assets\fonts\mullish\Mulish-Bold.ttf
        - asset: assets\fonts\mullish\Mulish-BoldItalic.ttf
        - asset: assets\fonts\mullish\Mulish-ExtraBold.ttf
        - asset: assets\fonts\mullish\Mulish-ExtraBoldItalic.ttf
        - asset: assets\fonts\mullish\Mulish-ExtraLight.ttf
        - asset: assets\fonts\mullish\Mulish-ExtraLightItalic.ttf
        - asset: assets\fonts\mullish\Mulish-Italic.ttf
        - asset: assets\fonts\mullish\Mulish-Light.ttf
        - asset: assets\fonts\mullish\Mulish-LightItalic.ttf
        - asset: assets\fonts\mullish\Mulish-Medium.ttf
        - asset: assets\fonts\mullish\Mulish-MediumItalic.ttf
        - asset: assets\fonts\mullish\Mulish-Regular.ttf
        - asset: assets\fonts\mullish\Mulish-SemiBold.ttf
        - asset: assets\fonts\mullish\Mulish-SemiBoldItalic.ttf
